import { readdir, readFile, realpath } from "node:fs/promises";
import { extname, relative, resolve, sep } from "node:path";
import type { HttpMethod } from "../domain/types.js";
import { PublicError } from "../security/errors.js";
import type { DiscoveredApiCall, EnvironmentReference, RepositoryFinding, RepositoryReport } from "./types.js";

const SOURCE_EXTENSIONS = new Set([".js", ".jsx", ".ts", ".tsx", ".py", ".java"]);
const IGNORED_DIRECTORIES = new Set([".git", "node_modules", "dist", "build", "coverage", ".venv", "target"]);
const HTTP_METHODS = new Set<HttpMethod>(["GET", "POST", "PUT", "PATCH", "DELETE"]);
export interface RepositoryScanOptions { root: string; openApiDocument: unknown; maxFiles?: number; maxFileBytes?: number }
interface OpenApiOperation { method: HttpMethod; path: string; id: string; pattern: RegExp }
function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new PublicError("INVALID_OPENAPI", `${label} must be an object`); return value as Record<string, unknown>; }
function pathPattern(path: string): RegExp { const escaped = path.split(/(\{[^}]+\})/g).map((part) => /^\{[^}]+\}$/.test(part) ? "[^/]+" : part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join(""); return new RegExp(`^${escaped}/?$`); }
function openApiOperations(document: unknown): OpenApiOperation[] { const root = object(document, "OpenAPI document"); if (typeof root.openapi !== "string" || !root.openapi.startsWith("3.")) throw new PublicError("INVALID_OPENAPI", "Only OpenAPI 3.x documents are supported"); const paths = object(root.paths, "OpenAPI paths"); const operations: OpenApiOperation[] = []; for (const [path, raw] of Object.entries(paths)) { const item = object(raw, `OpenAPI path ${path}`); for (const method of HTTP_METHODS) if (item[method.toLowerCase()] !== undefined) operations.push({ method, path, id: `${method} ${path}`, pattern: pathPattern(path) }); } return operations; }
function lineAt(source: string, index: number): number { return source.slice(0, index).split("\n").length; }
function relativeFile(root: string, file: string): string { return relative(root, file).split(sep).join("/"); }
function parseEnvExample(source: string): Set<string> { return new Set(source.split(/\r?\n/).flatMap((line) => { const match = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/); return match?.[1] ? [match[1]] : []; })); }
function method(value: string | undefined, fallback: HttpMethod = "GET"): HttpMethod { const upper = value?.toUpperCase() as HttpMethod; return HTTP_METHODS.has(upper) ? upper : fallback; }
function literal(value: string): string | null { const match = value.match(/^["'`]([^"'`$\r\n]+)["'`]$/); return match?.[1] ?? null; }
function matchOperation(operations: OpenApiOperation[], url: string, verb: HttpMethod): OpenApiOperation | undefined { try { const parsed = new URL(url); return operations.find((candidate) => candidate.method === verb && candidate.pattern.test(parsed.pathname)); } catch { return undefined; } }
function sourceCall(client: DiscoveredApiCall["client"], root: string, file: string, source: string, index: number, url: string, verb: HttpMethod, snippet: string, operations: OpenApiOperation[]): DiscoveredApiCall { const operation = matchOperation(operations, url, verb); return { client, file: relativeFile(root, file), line: lineAt(source, index), method: verb, url, openApiOperation: operation?.id ?? null, headers: {}, body: null, sourceText: snippet.slice(0, 240) }; }
function scanSource(root: string, file: string, source: string, operations: OpenApiOperation[], declared: Set<string>): { calls: DiscoveredApiCall[]; environment: EnvironmentReference[]; findings: RepositoryFinding[] } {
  const relativePath = relativeFile(root, file), calls: DiscoveredApiCall[] = [], environment: EnvironmentReference[] = [], findings: RepositoryFinding[] = []; const seen = new Set<number>();
  const add = (call: DiscoveredApiCall, index: number) => { calls.push(call); seen.add(index); if (!call.openApiOperation) findings.push({ code: "OPENAPI_OPERATION_MISSING", severity: "error", file: call.file, line: call.line, message: `${call.method} ${call.url} is not declared by the supplied OpenAPI document` }); };
  for (const match of source.matchAll(/\bfetch\s*\(\s*(["'`][^"'`$\r\n]+["'`])/g)) { if (match.index === undefined || !match[1]) continue; const url = literal(match[1]); if (url) { const snippet = source.slice(match.index, match.index + 800); const verb = method(snippet.match(/\bmethod\s*:\s*["'](GET|POST|PUT|PATCH|DELETE)["']/i)?.[1]); add(sourceCall("fetch", root, file, source, match.index, url, verb, snippet, operations), match.index); } }
  for (const match of source.matchAll(/\baxios\.(get|post|put|patch|delete)\s*\(\s*(["'`][^"'`$\r\n]+["'`])/gi)) { if (match.index === undefined || !match[2]) continue; const url = literal(match[2]); if (url) add(sourceCall("axios", root, file, source, match.index, url, method(match[1]), source.slice(match.index, match.index + 800), operations), match.index); }
  for (const match of source.matchAll(/\brequests\.(get|post|put|patch|delete)\s*\(\s*(["'`][^"'`$\r\n]+["'`])/gi)) { if (match.index === undefined || !match[2]) continue; const url = literal(match[2]); if (url) add(sourceCall("requests", root, file, source, match.index, url, method(match[1]), source.slice(match.index, match.index + 800), operations), match.index); }
  for (const match of source.matchAll(/Request\.Builder\(\)[\s\S]{0,800}?\.url\(\s*(["'`][^"'`$\r\n]+["'`])[\s\S]{0,300}?\.build\(\)/g)) { if (match.index === undefined || !match[1]) continue; const url = literal(match[1]); if (url) { const snippet = source.slice(match.index, match.index + 1000); const verbMatch = snippet.match(/\.([a-z]+)\s*\(/i)?.[1]; add(sourceCall("okhttp", root, file, source, match.index, url, method(verbMatch, "GET"), snippet, operations), match.index); } }
  for (const match of source.matchAll(/\bfetch\s*\(\s*(?!["'`])[^)]*/gi)) if (match.index !== undefined && !seen.has(match.index)) { const finding = { severity: "info" as const, file: relativePath, line: lineAt(source, match.index), message: "Dynamic URL was not interpreted; V2 only accepts literal HTTP(S) targets" }; findings.push({ ...finding, code: "DYNAMIC_URL_UNSUPPORTED" }); findings.push({ ...finding, code: "DYNAMIC_FETCH_UNSUPPORTED" }); }
  for (const match of source.matchAll(/\b(?:axios|requests)\.(?:get|post|put|patch|delete)\s*\(\s*(?!["'`])[^)]*/gi)) if (match.index !== undefined && !seen.has(match.index)) findings.push({ code: "DYNAMIC_URL_UNSUPPORTED", severity: "info", file: relativePath, line: lineAt(source, match.index), message: "Dynamic URL was not interpreted; V2 only accepts literal HTTP(S) targets" });
  const seenEnvironment = new Set<string>(); for (const pattern of [/\bprocess\.env\.([A-Z][A-Z0-9_]*)\b/g, /\bimport\.meta\.env\.([A-Z][A-Z0-9_]*)\b/g, /\bos\.environ(?:\.get)?\(\s*["']([A-Z][A-Z0-9_]*)["']/g, /\bSystem\.getenv\(\s*["']([A-Z][A-Z0-9_]*)["']/g]) for (const match of source.matchAll(pattern)) { const name = match[1]; if (!name || match.index === undefined || seenEnvironment.has(name)) continue; seenEnvironment.add(name); const declaredInExample = declared.has(name); environment.push({ name, declaredInExample, file: relativePath, line: lineAt(source, match.index) }); if (!declaredInExample) findings.push({ code: "ENV_NOT_DECLARED", severity: "warning", file: relativePath, line: lineAt(source, match.index), message: `${name} is referenced in source but missing from .env.example` }); }
  return { calls, environment, findings };
}
export async function scanRepository(options: RepositoryScanOptions): Promise<RepositoryReport> {
  const root = await realpath(resolve(options.root)); const maxFiles = options.maxFiles ?? 500, maxFileBytes = options.maxFileBytes ?? 512_000; if (!Number.isInteger(maxFiles) || maxFiles < 1 || maxFiles > 10_000) throw new PublicError("INVALID_SCAN_LIMIT", "maxFiles must be between 1 and 10000"); if (!Number.isInteger(maxFileBytes) || maxFileBytes < 1_024 || maxFileBytes > 5_000_000) throw new PublicError("INVALID_SCAN_LIMIT", "maxFileBytes must be between 1024 and 5000000"); const operations = openApiOperations(options.openApiDocument); let declared = new Set<string>(); try { declared = parseEnvExample(await readFile(resolve(root, ".env.example"), "utf8")); } catch (error) { if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error; }
  const files: string[] = []; async function walk(directory: string): Promise<void> { for (const entry of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) { if (entry.isSymbolicLink()) continue; const path = resolve(directory, entry.name); if (entry.isDirectory()) { if (!IGNORED_DIRECTORIES.has(entry.name)) await walk(path); } else if (entry.isFile() && SOURCE_EXTENSIONS.has(extname(entry.name).toLowerCase())) { files.push(path); if (files.length > maxFiles) throw new PublicError("SCAN_FILE_LIMIT", `Repository exceeds ${maxFiles} source file limit`, 413); } } }
  await walk(root); const apiCalls: DiscoveredApiCall[] = [], environmentReferences: EnvironmentReference[] = [], findings: RepositoryFinding[] = []; for (const file of files) { const buffer = await readFile(file); if (buffer.byteLength > maxFileBytes) { findings.push({ code: "FILE_TOO_LARGE", severity: "warning", file: relativeFile(root, file), line: 1, message: `File exceeds ${maxFileBytes} byte scan limit` }); continue; } const result = scanSource(root, file, buffer.toString("utf8"), operations, declared); apiCalls.push(...result.calls); environmentReferences.push(...result.environment); findings.push(...result.findings); }
  return { root, scannedFiles: files.length, apiCalls, environmentReferences, findings, summary: { calls: apiCalls.length, matchedOperations: apiCalls.filter((call) => call.openApiOperation !== null).length, errors: findings.filter((f) => f.severity === "error").length, warnings: findings.filter((f) => f.severity === "warning").length } };
}
